// Generated by scripts/sync-maps.ts from valorant-api.com /v1/maps on 2026-10-01.
// Community data, not an official Riot source. Do not edit by hand; run `pnpm maps:sync`.
import type { MapData } from "./maps.js";

export const MAP_DATA: readonly MapData[] = [
  {
    mapPath: "/Game/Maps/Infinity/Infinity",
    displayName: "Abyss",
    xMultiplier: 0.000081,
    yMultiplier: -0.000081,
    xScalarToAdd: 0.5,
    yScalarToAdd: 0.5,
    callouts: [
      {
        name: "Bridge",
        region: "A",
        pos: {
          x: 5700,
          y: -375,
          z: 900,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 2800,
          y: -2450,
          z: 1075,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 3250,
          y: 3400,
          z: 975,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 3800,
          y: 1650,
          z: 975,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 4300,
          y: -200,
          z: 800,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 950,
          y: 4950,
          z: 850,
        },
      },
      {
        name: "Tower",
        region: "A",
        pos: {
          x: 3025,
          y: -125,
          z: 1350,
        },
      },
      {
        name: "Bend",
        region: "Mid",
        pos: {
          x: -1700,
          y: 1075,
          z: 950,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: -2000,
          y: -2350,
          z: 925,
        },
      },
      {
        name: "Lobby",
        region: "B",
        pos: {
          x: -3650,
          y: 4025,
          z: 400,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: -4450,
          y: 1525,
          z: 525,
        },
      },
      {
        name: "Nest",
        region: "B",
        pos: {
          x: -4975,
          y: 2150,
          z: 900,
        },
      },
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: -400,
          y: 575,
          z: 975,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: -4425,
          y: -1175,
          z: 700,
        },
      },
      {
        name: "Catwalk",
        region: "Mid",
        pos: {
          x: 600,
          y: 525,
          z: 1300,
        },
      },
      {
        name: "Danger",
        region: "B",
        pos: {
          x: -5850,
          y: 700,
          z: 625,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 950,
          y: -5275,
          z: 1125,
        },
      },
      {
        name: "Library",
        region: "Mid",
        pos: {
          x: -325,
          y: -600,
          z: 975,
        },
      },
      {
        name: "Secret",
        region: "A",
        pos: {
          x: 3775,
          y: -3850,
          z: 1025,
        },
      },
      {
        name: "Security",
        region: "A",
        pos: {
          x: 4900,
          y: -2975,
          z: 950,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 775,
          y: -2375,
          z: 1075,
        },
      },
      {
        name: "Tower",
        region: "B",
        pos: {
          x: -3925,
          y: -2500,
          z: 1100,
        },
      },
      {
        name: "Vent",
        region: "A",
        pos: {
          x: 1700,
          y: -325,
          z: 1325,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Ascent/Ascent",
    displayName: "Ascent",
    xMultiplier: 0.00007,
    yMultiplier: -0.00007,
    xScalarToAdd: 0.813895,
    yScalarToAdd: 0.573242,
    callouts: [
      {
        name: "Tree",
        region: "A",
        pos: {
          x: 3981,
          y: -5939,
          z: 400,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 4489,
          y: -3014,
          z: 400,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 5322,
          y: -4710,
          z: 400,
        },
      },
      {
        name: "Window",
        region: "A",
        pos: {
          x: 4023,
          y: -8181,
          z: 803,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 6154,
          y: -6626,
          z: 500,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 60,
          y: 50,
          z: 190,
        },
      },
      {
        name: "Lobby",
        region: "B",
        pos: {
          x: -1491,
          y: -1390,
          z: 200,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: -1984,
          y: -5841,
          z: 100,
        },
      },
      {
        name: "Boat House",
        region: "B",
        pos: {
          x: -4485,
          y: -7763,
          z: -105,
        },
      },
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: 1122,
          y: -5952,
          z: 200,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: -2344,
          y: -7549,
          z: 99,
        },
      },
      {
        name: "Catwalk",
        region: "Mid",
        pos: {
          x: 2316,
          y: -4127,
          z: 416,
        },
      },
      {
        name: "Cubby",
        region: "Mid",
        pos: {
          x: 3387,
          y: -5130,
          z: 400,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 1995,
          y: -9745,
          z: 300,
        },
      },
      {
        name: "Garden",
        region: "A",
        pos: {
          x: 3774,
          y: -7551,
          z: 570,
        },
      },
      {
        name: "Market",
        region: "Mid",
        pos: {
          x: 1089,
          y: -7363,
          z: 307,
        },
      },
      {
        name: "Courtyard",
        region: "Mid",
        pos: {
          x: 1223,
          y: -4587,
          z: 200,
        },
      },
      {
        name: "Link",
        region: "Mid",
        pos: {
          x: -632,
          y: -4280,
          z: 200,
        },
      },
      {
        name: "Pizza",
        region: "Mid",
        pos: {
          x: 1802,
          y: -7262,
          z: 300,
        },
      },
      {
        name: "Rafters",
        region: "A",
        pos: {
          x: 6130,
          y: -8210,
          z: 806,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 2754,
          y: -2130,
          z: 400,
        },
      },
      {
        name: "Wine",
        region: "A",
        pos: {
          x: 7359,
          y: -4689,
          z: 300,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Duality/Duality",
    displayName: "Bind",
    xMultiplier: 0.000059,
    yMultiplier: -0.000059,
    xScalarToAdd: 0.576941,
    yScalarToAdd: 0.967566,
    callouts: [
      {
        name: "Exit",
        region: "A",
        pos: {
          x: 7550,
          y: 5874,
          z: 200,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 6366,
          y: -1007,
          z: 200,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 6113,
          y: 3159,
          z: 102,
        },
      },
      {
        name: "Short",
        region: "A",
        pos: {
          x: 7983,
          y: 804,
          z: 200,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 10748,
          y: 2664,
          z: 100,
        },
      },
      {
        name: "Teleporter",
        region: "A",
        pos: {
          x: 9432,
          y: 490,
          z: 200,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 162,
          y: 78,
          z: -190,
        },
      },
      {
        name: "Exit",
        region: "B",
        pos: {
          x: 8921,
          y: -1763,
          z: 506,
        },
      },
      {
        name: "Hall",
        region: "B",
        pos: {
          x: 12982,
          y: -4942,
          z: 300,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: 6362,
          y: -2621,
          z: 301,
        },
      },
      {
        name: "Fountain",
        region: "B",
        pos: {
          x: 5737,
          y: -5390,
          z: 107,
        },
      },
      {
        name: "Long",
        region: "B",
        pos: {
          x: 7667,
          y: -6513,
          z: 268,
        },
      },
      {
        name: "Short",
        region: "B",
        pos: {
          x: 7424,
          y: -3056,
          z: 361,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 11108,
          y: -4831,
          z: 367,
        },
      },
      {
        name: "Teleporter",
        region: "B",
        pos: {
          x: 9028,
          y: -7224,
          z: 300,
        },
      },
      {
        name: "Window",
        region: "B",
        pos: {
          x: 8827,
          y: -4309,
          z: 500,
        },
      },
      {
        name: "Bath",
        region: "A",
        pos: {
          x: 9107,
          y: 4450,
          z: 100,
        },
      },
      {
        name: "Cave",
        region: "Attacker Side",
        pos: {
          x: 3920,
          y: 257,
          z: 102,
        },
      },
      {
        name: "Cubby",
        region: "A",
        pos: {
          x: 8605,
          y: 175,
          z: 200,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 14642,
          y: -1018,
          z: 100,
        },
      },
      {
        name: "Elbow",
        region: "B",
        pos: {
          x: 11213,
          y: -7095,
          z: 304,
        },
      },
      {
        name: "Garden",
        region: "B",
        pos: {
          x: 9144,
          y: -5598,
          z: 300,
        },
      },
      {
        name: "Lamps",
        region: "A",
        pos: {
          x: 10649,
          y: 80,
          z: 204,
        },
      },
      {
        name: "Tower",
        region: "A",
        pos: {
          x: 12873,
          y: 2557,
          z: 400,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Foxtrot/Foxtrot",
    displayName: "Breeze",
    xMultiplier: 0.00007,
    yMultiplier: -0.00007,
    xScalarToAdd: 0.465123,
    yScalarToAdd: 0.833078,
    callouts: [
      {
        name: "Hall",
        region: "Mid",
        pos: {
          x: 4257,
          y: 2491,
          z: 213,
        },
      },
      {
        name: "Bridge",
        region: "A",
        pos: {
          x: 8400,
          y: 3525,
          z: 1100,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 8900,
          y: 3525,
          z: 1100,
        },
      },
      {
        name: "Arches",
        region: "Defender Side",
        pos: {
          x: 9400,
          y: -1300,
          z: 1100,
        },
      },
      {
        name: "Wood Doors",
        region: "Mid",
        pos: {
          x: 4825,
          y: 2550,
          z: 500,
        },
      },
      {
        name: "Pillar",
        region: "Mid",
        pos: {
          x: 4175,
          y: 475,
          z: 200,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 6175,
          y: 525,
          z: 200,
        },
      },
      {
        name: "Nest",
        region: "Mid",
        pos: {
          x: 8650,
          y: 275,
          z: 200,
        },
      },
      {
        name: "Window",
        region: "B",
        pos: {
          x: 2225,
          y: -4175,
          z: 200,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: 3550,
          y: -4450,
          z: 200,
        },
      },
      {
        name: "Elbow",
        region: "B",
        pos: {
          x: 4675,
          y: -2900,
          z: 200,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 6450,
          y: -5650,
          z: 200,
        },
      },
      {
        name: "Tunnel",
        region: "B",
        pos: {
          x: 6450,
          y: -1450,
          z: 200,
        },
      },
      {
        name: "Ramp",
        region: "A",
        pos: {
          x: 7300,
          y: 2725,
          z: 1100,
        },
      },
      {
        name: "Back",
        region: "B",
        pos: {
          x: 7550,
          y: -5675,
          z: 200,
        },
      },
      {
        name: "Wall",
        region: "B",
        pos: {
          x: 8550,
          y: -3000,
          z: 200,
        },
      },
      {
        name: "Cannon",
        region: "Mid",
        pos: {
          x: 2900,
          y: -1850,
          z: 200,
        },
      },
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: 1575,
          y: 475,
          z: 200,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: -1250,
          y: 3400,
          z: 200,
        },
      },
      {
        name: "Shop",
        region: "A",
        pos: {
          x: 2150,
          y: 4250,
          z: 200,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 4825,
          y: 6325,
          z: 200,
        },
      },
      {
        name: "Pyramids",
        region: "A",
        pos: {
          x: 5200,
          y: 5450,
          z: 200,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: -575,
          y: -450,
          z: 200,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Rook/Rook",
    displayName: "Corrode",
    xMultiplier: 0.00007,
    yMultiplier: -0.00007,
    xScalarToAdd: 0.526158,
    yScalarToAdd: 0.5,
    callouts: [
      {
        name: "Crane",
        region: "A",
        pos: {
          x: 4458,
          y: -3999,
          z: 600,
        },
      },
      {
        name: "Elbow",
        region: "A",
        pos: {
          x: 5583,
          y: -2074,
          z: 700,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 1783,
          y: -1050,
          z: 675,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 4333,
          y: 2600,
          z: 700,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 5933,
          y: 1225,
          z: 700,
        },
      },
      {
        name: "Pocket",
        region: "A",
        pos: {
          x: 5583,
          y: -799,
          z: 700,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 3458,
          y: -1825,
          z: 700,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: -25,
          y: 5675,
          z: 575,
        },
      },
      {
        name: "Yard",
        region: "A",
        pos: {
          x: 4333,
          y: -800,
          z: 700,
        },
      },
      {
        name: "Arch",
        region: "B",
        pos: {
          x: -3217,
          y: -4400,
          z: 600,
        },
      },
      {
        name: "Elbow",
        region: "B",
        pos: {
          x: -5592,
          y: -2925,
          z: 700,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: -1292,
          y: -1825,
          z: 700,
        },
      },
      {
        name: "Lobby",
        region: "B",
        pos: {
          x: -1667,
          y: 2775,
          z: 700,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: -2717,
          y: 750,
          z: 700,
        },
      },
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: 133,
          y: 175,
          z: 700,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: -2717,
          y: -1175,
          z: 700,
        },
      },
      {
        name: "Tower",
        region: "B",
        pos: {
          x: -3517,
          y: -2925,
          z: 700,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 8,
          y: -5750,
          z: 700,
        },
      },
      {
        name: "Stairs",
        region: "Mid",
        pos: {
          x: 133,
          y: -1475,
          z: 700,
        },
      },
      {
        name: "Window",
        region: "Mid",
        pos: {
          x: 133,
          y: -3100,
          z: 700,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 133,
          y: -1825,
          z: 700,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Canyon/Canyon",
    displayName: "Fracture",
    xMultiplier: 0.000078,
    yMultiplier: -0.000078,
    xScalarToAdd: 0.556952,
    yScalarToAdd: 1.155886,
    callouts: [
      {
        name: "Bridge",
        region: "Attacker Side",
        pos: {
          x: 13204,
          y: -756,
          z: 253,
        },
      },
      {
        name: "Bench",
        region: "B",
        pos: {
          x: 11473,
          y: -2897,
          z: 400,
        },
      },
      {
        name: "Arcade",
        region: "B",
        pos: {
          x: 10181,
          y: -4179,
          z: 500,
        },
      },
      {
        name: "Tower",
        region: "B",
        pos: {
          x: 9155,
          y: -5601,
          z: 1000,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 8178,
          y: -5942,
          z: 747,
        },
      },
      {
        name: "Generator",
        region: "B",
        pos: {
          x: 8362,
          y: -3380,
          z: 550,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: 9198,
          y: -2741,
          z: 650,
        },
      },
      {
        name: "Canteen",
        region: "B",
        pos: {
          x: 7111,
          y: -3138,
          z: 547,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 8578,
          y: 1302,
          z: 650,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 9156,
          y: -677,
          z: 650,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: 5967,
          y: -5343,
          z: 425,
        },
      },
      {
        name: "Tree",
        region: "B",
        pos: {
          x: 4965,
          y: -4109,
          z: 300,
        },
      },
      {
        name: "Tunnel",
        region: "B",
        pos: {
          x: 7402,
          y: -4058,
          z: 109,
        },
      },
      {
        name: "Hall",
        region: "A",
        pos: {
          x: 5064,
          y: 2058,
          z: 600,
        },
      },
      {
        name: "Door",
        region: "A",
        pos: {
          x: 5808,
          y: 1940,
          z: 602,
        },
      },
      {
        name: "Rope",
        region: "A",
        pos: {
          x: 6639,
          y: 1053,
          z: 493,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 5879,
          y: 3451,
          z: 550,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 8126,
          y: 3374,
          z: 550,
        },
      },
      {
        name: "Drop",
        region: "A",
        pos: {
          x: 9307,
          y: 2826,
          z: 850,
        },
      },
      {
        name: "Dish",
        region: "A",
        pos: {
          x: 11297,
          y: 1392,
          z: 623,
        },
      },
      {
        name: "Gate",
        region: "A",
        pos: {
          x: 12962,
          y: 1565,
          z: 450,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 4346,
          y: -948,
          z: 307,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Triad/Triad",
    displayName: "Haven",
    xMultiplier: 0.000075,
    yMultiplier: -0.000075,
    xScalarToAdd: 1.09345,
    yScalarToAdd: 0.642728,
    callouts: [
      {
        name: "Garden",
        region: "A",
        pos: {
          x: 3100,
          y: -4684,
          z: 300,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 4244,
          y: -10716,
          z: 300,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 3439,
          y: -6260,
          z: 300,
        },
      },
      {
        name: "Long",
        region: "A",
        pos: {
          x: 6210,
          y: -6901,
          z: 100,
        },
      },
      {
        name: "Sewer",
        region: "A",
        pos: {
          x: 3453,
          y: -7916,
          z: 0,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 6309,
          y: -9226,
          z: 300,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 1742,
          y: -2643,
          z: 278,
        },
      },
      {
        name: "Back",
        region: "B",
        pos: {
          x: 1966,
          y: -10665,
          z: 300,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 1885,
          y: -9231,
          z: 700,
        },
      },
      {
        name: "Link",
        region: "C",
        pos: {
          x: -88,
          y: -10004,
          z: 300,
        },
      },
      {
        name: "Lobby",
        region: "C",
        pos: {
          x: -1642,
          y: -5720,
          z: 101,
        },
      },
      {
        name: "Long",
        region: "C",
        pos: {
          x: -3357,
          y: -5991,
          z: 100,
        },
      },
      {
        name: "Garage",
        region: "C",
        pos: {
          x: 180,
          y: -8000,
          z: 100,
        },
      },
      {
        name: "Window",
        region: "C",
        pos: {
          x: -10,
          y: -8993,
          z: 300,
        },
      },
      {
        name: "Site",
        region: "C",
        pos: {
          x: -2378,
          y: -9011,
          z: 200,
        },
      },
      {
        name: "Cubby",
        region: "C",
        pos: {
          x: -2120,
          y: -6562,
          z: 200,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 2946,
          y: -12715,
          z: 300,
        },
      },
      {
        name: "Doors",
        region: "Mid",
        pos: {
          x: 151,
          y: -6263,
          z: 95,
        },
      },
      {
        name: "Courtyard",
        region: "Mid",
        pos: {
          x: 1822,
          y: -6713,
          z: 95,
        },
      },
      {
        name: "Window",
        region: "Mid",
        pos: {
          x: 1950,
          y: -5568,
          z: 300,
        },
      },
      {
        name: "Tower",
        region: "A",
        pos: {
          x: 6721,
          y: -10473,
          z: 900,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Port/Port",
    displayName: "Icebox",
    xMultiplier: 0.000072,
    yMultiplier: -0.000072,
    xScalarToAdd: 0.460214,
    yScalarToAdd: 0.304687,
    callouts: [
      {
        name: "Garage",
        region: "B",
        pos: {
          x: -1250,
          y: -1425,
          z: 100,
        },
      },
      {
        name: "Belt",
        region: "A",
        pos: {
          x: -7200,
          y: -850,
          z: 100,
        },
      },
      {
        name: "Nest",
        region: "A",
        pos: {
          x: -6650,
          y: 900,
          z: 1675,
        },
      },
      {
        name: "Pipes",
        region: "A",
        pos: {
          x: -6150,
          y: 450,
          z: 100,
        },
      },
      {
        name: "Rafters",
        region: "A",
        pos: {
          x: -6450,
          y: 4250,
          z: 500,
        },
      },
      {
        name: "Screen",
        region: "A",
        pos: {
          x: -5100,
          y: 3325,
          z: 100,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: -6400,
          y: 3200,
          z: 200,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: -3925,
          y: -4450,
          z: 600,
        },
      },
      {
        name: "Yellow",
        region: "B",
        pos: {
          x: 2050,
          y: -25,
          z: 100,
        },
      },
      {
        name: "Back",
        region: "B",
        pos: {
          x: 251,
          y: 4269,
          z: 100,
        },
      },
      {
        name: "Cubby",
        region: "B",
        pos: {
          x: 1050,
          y: -975,
          z: 100,
        },
      },
      {
        name: "Green",
        region: "B",
        pos: {
          x: -450,
          y: -700,
          z: 100,
        },
      },
      {
        name: "Hall",
        region: "B",
        pos: {
          x: 300,
          y: 3050,
          z: 500,
        },
      },
      {
        name: "Hut",
        region: "B",
        pos: {
          x: -1425,
          y: 4400,
          z: 450,
        },
      },
      {
        name: "Kitchen",
        region: "B",
        pos: {
          x: -2221,
          y: 3404,
          z: 479,
        },
      },
      {
        name: "Orange",
        region: "B",
        pos: {
          x: -632,
          y: 1700,
          z: 100,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 1725,
          y: 2575,
          z: 100,
        },
      },
      {
        name: "Snowman",
        region: "B",
        pos: {
          x: 2250,
          y: 3960,
          z: 100,
        },
      },
      {
        name: "Snow Pile",
        region: "B",
        pos: {
          x: -1775,
          y: 2500,
          z: 100,
        },
      },
      {
        name: "Tube",
        region: "B",
        pos: {
          x: -2300,
          y: 1275,
          z: 463,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: -3750,
          y: 7075,
          z: 330,
        },
      },
      {
        name: "Blue",
        region: "Mid",
        pos: {
          x: -2825,
          y: 975,
          z: 100,
        },
      },
      {
        name: "Boiler",
        region: "Mid",
        pos: {
          x: -3375,
          y: 2925,
          z: 271,
        },
      },
      {
        name: "Pallet",
        region: "Mid",
        pos: {
          x: -4450,
          y: 1775,
          z: 100,
        },
      },
      {
        name: "Fence",
        region: "B",
        pos: {
          x: 363,
          y: 3595,
          z: 72,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Jam/Jam",
    displayName: "Lotus",
    xMultiplier: 0.000072,
    yMultiplier: -0.000072,
    xScalarToAdd: 0.454789,
    yScalarToAdd: 0.917752,
    callouts: [
      {
        name: "Top",
        region: "A",
        pos: {
          x: 9260,
          y: 5046,
          z: 80,
        },
      },
      {
        name: "Drop",
        region: "A",
        pos: {
          x: 9516,
          y: 6093,
          z: 233,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 7736,
          y: 5557,
          z: 233,
        },
      },
      {
        name: "Hut",
        region: "A",
        pos: {
          x: 7917,
          y: 5557,
          z: 233,
        },
      },
      {
        name: "Tree",
        region: "A",
        pos: {
          x: 6150,
          y: 5557,
          z: 233,
        },
      },
      {
        name: "Door",
        region: "A",
        pos: {
          x: 5609,
          y: 5204,
          z: 233,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 5288,
          y: 4160,
          z: 233,
        },
      },
      {
        name: "Rubble",
        region: "A",
        pos: {
          x: 4401,
          y: 4918,
          z: 233,
        },
      },
      {
        name: "Root",
        region: "A",
        pos: {
          x: 4401,
          y: 3294,
          z: 233,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 2686,
          y: 2927,
          z: 233,
        },
      },
      {
        name: "Lobby",
        region: "C",
        pos: {
          x: 1404,
          y: -1577,
          z: 100,
        },
      },
      {
        name: "Pillars",
        region: "B",
        pos: {
          x: 3565,
          y: 668,
          z: 167,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: 4877,
          y: -48,
          z: 167,
        },
      },
      {
        name: "Door",
        region: "C",
        pos: {
          x: 4819,
          y: -1753,
          z: 233,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 6368,
          y: 668,
          z: 167,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 6011,
          y: 2088,
          z: 167,
        },
      },
      {
        name: "Upper",
        region: "B",
        pos: {
          x: 7683,
          y: 1517,
          z: 167,
        },
      },
      {
        name: "Waterfall",
        region: "C",
        pos: {
          x: 6720,
          y: -1994,
          z: 72,
        },
      },
      {
        name: "Link",
        region: "C",
        pos: {
          x: 7504,
          y: -1378,
          z: 72,
        },
      },
      {
        name: "Stairs",
        region: "A",
        pos: {
          x: 8258,
          y: 3861,
          z: 233,
        },
      },
      {
        name: "Mound",
        region: "C",
        pos: {
          x: 3864,
          y: -1577,
          z: 125,
        },
      },
      {
        name: "Main",
        region: "C",
        pos: {
          x: 5311,
          y: -3148,
          z: 75,
        },
      },
      {
        name: "Bend",
        region: "C",
        pos: {
          x: 5658,
          y: -5281,
          z: 80,
        },
      },
      {
        name: "Site",
        region: "C",
        pos: {
          x: 6677,
          y: -4266,
          z: 80,
        },
      },
      {
        name: "Hall",
        region: "C",
        pos: {
          x: 7902,
          y: -4266,
          z: 80,
        },
      },
      {
        name: "Gravel",
        region: "C",
        pos: {
          x: 8937,
          y: -1752,
          z: 80,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 9687,
          y: 1698,
          z: 80,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 1401,
          y: 777,
          z: 233,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Pitt/Pitt",
    displayName: "Pearl",
    xMultiplier: 0.000078,
    yMultiplier: -0.000078,
    xScalarToAdd: 0.480469,
    yScalarToAdd: 0.916016,
    callouts: [
      {
        name: "Hall",
        region: "B",
        pos: {
          x: 7496,
          y: -4954,
          z: 250,
        },
      },
      {
        name: "Doors",
        region: "Mid",
        pos: {
          x: 4701,
          y: 597,
          z: 687,
        },
      },
      {
        name: "Connector",
        region: "Mid",
        pos: {
          x: 6047,
          y: 1800,
          z: 497,
        },
      },
      {
        name: "Water",
        region: "Defender Side",
        pos: {
          x: 7808,
          y: 1800,
          z: 368,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 11092,
          y: 379,
          z: 397,
        },
      },
      {
        name: "Flowers",
        region: "A",
        pos: {
          x: 9264,
          y: 2507,
          z: 497,
        },
      },
      {
        name: "Secret",
        region: "A",
        pos: {
          x: 10458,
          y: 3832,
          z: 301,
        },
      },
      {
        name: "Dugout",
        region: "A",
        pos: {
          x: 7661,
          y: 5854,
          z: 308,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 6614,
          y: 5570,
          z: 309,
        },
      },
      {
        name: "Records",
        region: "Defender Side",
        pos: {
          x: 8973,
          y: -1470,
          z: 497,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 2075,
          y: 725,
          z: 1000,
        },
      },
      {
        name: "Tunnel",
        region: "B",
        pos: {
          x: 8973,
          y: -2155,
          z: 497,
        },
      },
      {
        name: "Tower",
        region: "B",
        pos: {
          x: 8533,
          y: -2851,
          z: 762,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 6369,
          y: 3825,
          z: 300,
        },
      },
      {
        name: "Restaurant",
        region: "A",
        pos: {
          x: 4430,
          y: 2813,
          z: 300,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: 4503,
          y: -592,
          z: 265,
        },
      },
      {
        name: "Art",
        region: "A",
        pos: {
          x: 4562,
          y: 3407,
          z: 265,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 6055,
          y: 3783,
          z: 265,
        },
      },
      {
        name: "Plaza",
        region: "Mid",
        pos: {
          x: 2750,
          y: -325,
          z: 775,
        },
      },
      {
        name: "Shops",
        region: "Mid",
        pos: {
          x: 800,
          y: -1450,
          z: 775,
        },
      },
      {
        name: "Club",
        region: "B",
        pos: {
          x: 800,
          y: -1450,
          z: 475,
        },
      },
      {
        name: "Ramp",
        region: "B",
        pos: {
          x: 1750,
          y: -3800,
          z: 250,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: 4050,
          y: -4375,
          z: 250,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 5800,
          y: -2850,
          z: 250,
        },
      },
      {
        name: "Screen",
        region: "B",
        pos: {
          x: 6260,
          y: -5001,
          z: 250,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: -550,
          y: -600,
          z: 1000,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Bonsai/Bonsai",
    displayName: "Split",
    xMultiplier: 0.000078,
    yMultiplier: -0.000078,
    xScalarToAdd: 0.842188,
    yScalarToAdd: 0.697578,
    callouts: [
      {
        name: "Back",
        region: "A",
        pos: {
          x: 7345,
          y: -7858,
          z: 0,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 6814,
          y: -2458,
          z: 300,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 6280,
          y: -4493,
          z: 200,
        },
      },
      {
        name: "Rafters",
        region: "A",
        pos: {
          x: 5435,
          y: -6258,
          z: 550,
        },
      },
      {
        name: "Ramps",
        region: "A",
        pos: {
          x: 4330,
          y: -4750,
          z: 590,
        },
      },
      {
        name: "Screens",
        region: "A",
        pos: {
          x: 5649,
          y: -8869,
          z: 200,
        },
      },
      {
        name: "Sewer",
        region: "A",
        pos: {
          x: 4863,
          y: -2367,
          z: 59,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 6589,
          y: -6761,
          z: 100,
        },
      },
      {
        name: "Tower",
        region: "A",
        pos: {
          x: 4637,
          y: -6748,
          z: 650,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 1902,
          y: 60,
          z: 300,
        },
      },
      {
        name: "Alley",
        region: "B",
        pos: {
          x: -1158,
          y: -8066,
          z: 400,
        },
      },
      {
        name: "Back",
        region: "B",
        pos: {
          x: -3107,
          y: -7417,
          z: 300,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: -28,
          y: -2370,
          z: 350,
        },
      },
      {
        name: "Garage",
        region: "B",
        pos: {
          x: -2191,
          y: -3848,
          z: 300,
        },
      },
      {
        name: "Rafters",
        region: "B",
        pos: {
          x: -637,
          y: -6071,
          z: 922,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: -2167,
          y: -6265,
          z: 400,
        },
      },
      {
        name: "Stairs",
        region: "B",
        pos: {
          x: 1061,
          y: -6761,
          z: 840,
        },
      },
      {
        name: "Tower",
        region: "B",
        pos: {
          x: 169,
          y: -5290,
          z: 900,
        },
      },
      {
        name: "Lobby",
        region: "B",
        pos: {
          x: -1272,
          y: -1984,
          z: 300,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 2142,
          y: -8965,
          z: 500,
        },
      },
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: 1923,
          y: -2899,
          z: 450,
        },
      },
      {
        name: "Mail",
        region: "Mid",
        pos: {
          x: 1155,
          y: -4809,
          z: 800,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 2022,
          y: -4597,
          z: 650,
        },
      },
      {
        name: "Vent",
        region: "Mid",
        pos: {
          x: 3155,
          y: -5339,
          z: 650,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Plummet/Plummet",
    displayName: "Summit",
    xMultiplier: 0.000075,
    yMultiplier: -0.000075,
    xScalarToAdd: 0.047401,
    yScalarToAdd: 0.978891,
    callouts: [
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: 7500,
          y: 5825,
          z: 425,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 4025,
          y: 6525,
          z: 425,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: 3175,
          y: 8625,
          z: 200,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: 5500,
          y: 8625,
          z: 200,
        },
      },
      {
        name: "Garden",
        region: "A",
        pos: {
          x: 7675,
          y: 9925,
          z: 200,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 7675,
          y: 11600,
          z: 200,
        },
      },
      {
        name: "Art",
        region: "A",
        pos: {
          x: 9525,
          y: 9925,
          z: 350,
        },
      },
      {
        name: "Cave",
        region: "A",
        pos: {
          x: 9525,
          y: 12125,
          z: 350,
        },
      },
      {
        name: "Hall",
        region: "A",
        pos: {
          x: 9525,
          y: 8600,
          z: 350,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 8250,
          y: 8050,
          z: 200,
        },
      },
      {
        name: "Lobby",
        region: "B",
        pos: {
          x: 5125,
          y: 3225,
          z: 100,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 12075,
          y: 6175,
          z: 675,
        },
      },
      {
        name: "Window",
        region: "Mid",
        pos: {
          x: 8700,
          y: 5825,
          z: 675,
        },
      },
      {
        name: "Gym",
        region: "B",
        pos: {
          x: 10525,
          y: 3100,
          z: 675,
        },
      },
      {
        name: "Trophy",
        region: "B",
        pos: {
          x: 9075,
          y: 3675,
          z: 425,
        },
      },
      {
        name: "Tower",
        region: "B",
        pos: {
          x: 10175,
          y: 1450,
          z: 675,
        },
      },
      {
        name: "Drop",
        region: "B",
        pos: {
          x: 9850,
          y: 75,
          z: 325,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: 8550,
          y: 1375,
          z: 325,
        },
      },
      {
        name: "Link",
        region: "B",
        pos: {
          x: 7500,
          y: 3775,
          z: 425,
        },
      },
      {
        name: "Fountain",
        region: "Mid",
        pos: {
          x: 5675,
          y: 6175,
          z: 425,
        },
      },
      {
        name: "Bend",
        region: "Mid",
        pos: {
          x: 6475,
          y: 7850,
          z: 425,
        },
      },
      {
        name: "Tiles",
        region: "Mid",
        pos: {
          x: 4961,
          y: 4234,
          z: 425,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: 6500,
          y: 1850,
          z: 425,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: 1100,
          y: -100,
          z: 200,
        },
      },
    ],
  },
  {
    mapPath: "/Game/Maps/Juliett/Juliett",
    displayName: "Sunset",
    xMultiplier: 0.000078,
    yMultiplier: -0.000078,
    xScalarToAdd: 0.5,
    yScalarToAdd: 0.515625,
    callouts: [
      {
        name: "Boba",
        region: "B",
        pos: {
          x: 2200,
          y: -4800,
          z: -200,
        },
      },
      {
        name: "Tiles",
        region: "Mid",
        pos: {
          x: -1800,
          y: 400,
          z: -200,
        },
      },
      {
        name: "Market",
        region: "B",
        pos: {
          x: -200,
          y: -3400,
          z: -200,
        },
      },
      {
        name: "Site",
        region: "B",
        pos: {
          x: -600,
          y: -5850,
          z: -200,
        },
      },
      {
        name: "Main",
        region: "B",
        pos: {
          x: -2000,
          y: -5650,
          z: -200,
        },
      },
      {
        name: "Lobby",
        region: "B",
        pos: {
          x: -3400,
          y: -2600,
          z: -200,
        },
      },
      {
        name: "Bottom",
        region: "Mid",
        pos: {
          x: -1800,
          y: -2025,
          z: -200,
        },
      },
      {
        name: "Courtyard",
        region: "Mid",
        pos: {
          x: -600,
          y: -1200,
          z: -200,
        },
      },
      {
        name: "Lobby",
        region: "A",
        pos: {
          x: -1800,
          y: 2000,
          z: -200,
        },
      },
      {
        name: "Main",
        region: "A",
        pos: {
          x: -400,
          y: 2200,
          z: -200,
        },
      },
      {
        name: "Link",
        region: "A",
        pos: {
          x: 2200,
          y: 3000,
          z: -200,
        },
      },
      {
        name: "Site",
        region: "A",
        pos: {
          x: 1000,
          y: 3200,
          z: -200,
        },
      },
      {
        name: "Elbow",
        region: "A",
        pos: {
          x: 200,
          y: 4200,
          z: -200,
        },
      },
      {
        name: "Alley",
        region: "A",
        pos: {
          x: 3400,
          y: 3600,
          z: -200,
        },
      },
      {
        name: "Spawn",
        region: "Defender Side",
        pos: {
          x: 3805,
          y: -1989,
          z: -198,
        },
      },
      {
        name: "Top",
        region: "Mid",
        pos: {
          x: 2000,
          y: -2000,
          z: -200,
        },
      },
      {
        name: "Spawn",
        region: "Attacker Side",
        pos: {
          x: -6025,
          y: -400,
          z: -200,
        },
      },
    ],
  },
];
