/**
 * Pulls per-map calibration and callout points from valorant-api.com and writes
 * packages/shared/src/mapData.ts. Numbers only: no images or geometry are stored.
 * Run: pnpm maps:sync
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const Callout = z.object({
  regionName: z.string(),
  superRegionName: z.string(),
  location: z.object({ x: z.number(), y: z.number(), z: z.number() }),
});
const ApiMap = z.object({
  displayName: z.string(),
  mapUrl: z.string().nullish(),
  xMultiplier: z.number(),
  yMultiplier: z.number(),
  xScalarToAdd: z.number(),
  yScalarToAdd: z.number(),
  callouts: z.array(Callout).nullish(),
});

const res = await fetch("https://valorant-api.com/v1/maps");
const maps = z.object({ data: z.array(ApiMap) }).parse(await res.json()).data;

const usable = maps
  .filter((m) => m.mapUrl && m.xMultiplier !== 0 && (m.callouts?.length ?? 0) >= 8)
  .sort((a, b) => a.displayName.localeCompare(b.displayName))
  .map((m) => ({
    mapPath: m.mapUrl ?? "",
    displayName: m.displayName,
    xMultiplier: m.xMultiplier,
    yMultiplier: m.yMultiplier,
    xScalarToAdd: m.xScalarToAdd,
    yScalarToAdd: m.yScalarToAdd,
    callouts: (m.callouts ?? []).map((c) => ({
      name: c.regionName,
      region: c.superRegionName,
      pos: {
        x: Math.round(c.location.x),
        y: Math.round(c.location.y),
        z: Math.round(c.location.z),
      },
    })),
  }));

const out = fileURLToPath(new URL("../packages/shared/src/mapData.ts", import.meta.url));
writeFileSync(
  out,
  `// Generated by scripts/sync-maps.ts from valorant-api.com /v1/maps on ${new Date().toISOString().slice(0, 10)}.
// Community data, not an official Riot source. Do not edit by hand; run \`pnpm maps:sync\`.
import type { MapData } from "./maps.js";

export const MAP_DATA: readonly MapData[] = ${JSON.stringify(usable, null, 2)};
`,
);
console.log(`wrote ${usable.length} maps: ${usable.map((m) => m.displayName).join(", ")}`);
